### PR TITLE
MAJOR: PSR2 Compliance

### PR DESCRIPTION
**Pull request by shoaibali**
Ran this tool 

(https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-1-basic-coding-standard.md) 

for this
```
php-cs-fixer fix . --level=psr2 --fixers=-bracers
```

Then manually changed {} for classes, tabs instead of spaces and others..

### CODE REVIEW

**Comment by tractorcow** [comment]
@shoaibali we are looking at implementing full psr-2 standardisation, potentially soon. This could mean that we also transition to space-based indentation as well as the other features. :)

Hope you don't mind if I sit on your PR for a bit; There will be a public core committers hangout on the 18th at which we'll raise the issue.

**Comment by tractorcow** [comment]
See https://groups.google.com/forum/#!topic/silverstripe-dev/_ebPef7HgKQ

**Comment by shoaibali** [comment]
thanks @tractorcow , that will be an amazing milestone to achieve i.e full psr-2 compliance. 

Look forward to it.

**Comment by dhensby** [comment]
replaced by #207

**Pull request closed without merging**
