### PR TITLE
Added standard Travis config

### PR DESCRIPTION
**Pull request by helpfulrobot**
Hello!

I'm helpful robot. I noticed you had some non-standard Travis config. I think this is an improvement.

Have a nice day! [f-f-f-f-f-f-t]

### CODE REVIEW

**Comment by tractorcow** [comment]
I think your bot needs to detect branches that aren't 3.1 compatible.

**Comment by assertchris** [comment]
Pull requests for testing incompatible versions of framework?! What nonsense! Somebody better give this robot a good what-for...

**Comment by tractorcow** [comment]
Don't call @dhensby a robot =(

**Comment by assertchris** [comment]
I did no such thing. Had I said; "Merging pull requests for testing incompatible versions of framework..."

**Comment by tractorcow** [comment]
Haha.

**Pull request merged**
